; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Firebird SQL Agent
AppVerName=Firebird SQL Agent 1.0.12
AppPublisher=mariano podesta
AppPublisherURL=sourceforge.net/projects/fbagent
AppSupportURL=sourceforge.net/projects/fbagent
AppUpdatesURL=sourceforge.net/projects/fbagent
DefaultDirName={pf}\Firebird SQL Agent
DefaultGroupName=Firebird SQL Agent
AllowNoIcons=true
LicenseFile=D:\marianop\dev\delphi\lib\sil\1.5.9\programs\projects\fbagent\setup\License.txt
Compression=lzma
SolidCompression=true
OutputBaseFilename=fbagent-setup-1.0.12-2
ShowLanguageDialog=yes
AllowUNCPath=false
AppID={655F439E-223A-49CE-BF4D-452B23BA952C}
InternalCompressLevel=ultra
OutputDir=D:\marianop\dev\delphi\lib\sil\1.5.9\programs\projects\fbagent\setup\Output
AppCopyright=2005 Mariano Podestá

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}
Name: quicklaunchicon; Description: {cm:CreateQuickLaunchIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: ..\2\fbsqla.exe; DestDir: {app}; Flags: ignoreversion; Components: Firebird_SQL_Agent_Service
Source: ..\2\fbagent.exe; DestDir: {app}; Flags: ignoreversion
Source: ..\2\fbagent.xml; DestDir: {app}; Flags: ignoreversion
Source: ..\..\..\..\..\..\..\..\..\..\Program Files\Firebird SQL Agent\agent.fdb; DestDir: {app}; Flags: ignoreversion; Components: Firebird_SQL_Agent_Service
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: ..\tools\fbaliases.exe; DestDir: {app}; Flags: ignoreversion; Components: Firebird_SQL_Agent_Service

[Icons]
Name: {group}\{cm:UninstallProgram,Firebird SQL Agent}; Filename: {uninstallexe}
Name: {group}\Firebird SQL Agent; Filename: {app}\fbagent.exe
Name: {userdesktop}\Firebird SQL Agent; Filename: {app}\fbagent.exe; Tasks: desktopicon; IconIndex: 0

[Run]
Filename: net; Parameters: "stop ""firebird sql agent"""; StatusMsg: Stopping already installed service; Flags: runhidden; Components: Firebird_SQL_Agent_Service
Filename: {app}\fbaliases.exe; Parameters: D agent; Flags: runhidden; Components: Firebird_SQL_Agent_Service; WorkingDir: {app}
Filename: {app}\fbaliases.exe; Parameters: "A agent ""{app}\agent.fdb"""; WorkingDir: {app}; Description: "Register agent.fdb in aliases.conf as ""agent"""; Flags: postinstall; Components: Firebird_SQL_Agent_Service
Filename: {app}\fbsqla.exe; Parameters: -install -silent; Components: Firebird_SQL_Agent_Service
Filename: net; Parameters: "start ""firebird sql agent"""; StatusMsg: Starting service; Flags: runhidden; Components: Firebird_SQL_Agent_Service
; Filename: {app}\fbsqla.exe; Description: {cm:LaunchProgram,Firebird SQL Agent}; Flags: nowait runhidden; Parameters: -install

[UninstallDelete]
Name: {app}\*.log; Type: files
[UninstallRun]
Filename: net; Parameters: "stop ""firebird sql agent"""; StatusMsg: Stopping already installed service; Flags: runhidden; Components: Firebird_SQL_Agent_Service
Filename: {app}\fbaliases.exe; Parameters: D agent; WorkingDir: {app}; Flags: skipifdoesntexist; Components: Firebird_SQL_Agent_Service
Filename: {app}\fbsqla.exe; Parameters: -uninstall -silent; Components: Firebird_SQL_Agent_Service
[_ISTool]
UseAbsolutePaths=false
[Types]
Name: Server_Installation; Description: Service and Client GUI
Name: Client_Installation; Description: Client GUI
[Components]
Name: Firebird_SQL_Agent_Service; Description: Service; Types: Server_Installation
Name: Firebird_SQL_Agent_Client_GUI; Description: Client GUI; Types: Client_Installation Server_Installation
