program TestValue;

uses
  MemCheck,
  SilLayer,
  Forms,
  FmTestValue in 'FmTestValue.pas' {FormTestValueMain},
  SilLkValue in '..\..\..\..\..\source\lib\SilLkValue.pas',
  SilLiValueChar in '..\..\..\..\..\source\lib\SilLiValueChar.pas',
  SilLiValueAnsiString in '..\..\..\..\..\source\lib\SilLiValueAnsiString.pas',
  SilLiValueBoolean in '..\..\..\..\..\source\lib\SilLiValueBoolean.pas',
  SilLiValueByte in '..\..\..\..\..\source\lib\SilLiValueByte.pas',
  SilLiValue in '..\..\..\..\..\source\lib\SilLiValue.pas',
  SilLiValueCurrency in '..\..\..\..\..\source\lib\SilLiValueCurrency.pas',
  SilLiValueDateTime in '..\..\..\..\..\source\lib\SilLiValueDateTime.pas',
  SilLiValueDouble in '..\..\..\..\..\source\lib\SilLiValueDouble.pas',
  SilLiValueGuid in '..\..\..\..\..\source\lib\SilLiValueGuid.pas',
  SilLiValueInteger in '..\..\..\..\..\source\lib\SilLiValueInteger.pas',
  SilLiValueInterface in '..\..\..\..\..\source\lib\SilLiValueInterface.pas',
  SilLiValueLargeInt in '..\..\..\..\..\source\lib\SilLiValueLargeInt.pas',
  SilLiValueList in '..\..\..\..\..\source\lib\SilLiValueList.pas',
  SilLiValueLongWord in '..\..\..\..\..\source\lib\SilLiValueLongWord.pas',
  SilLiValueVariant in '..\..\..\..\..\source\lib\SilLiValueVariant.pas',
  SilLiValueWideString in '..\..\..\..\..\source\lib\SilLiValueWideString.pas',
  SilLiValueWord in '..\..\..\..\..\source\lib\SilLiValueWord.pas',
  SilLiValueShortint in '..\..\..\..\..\source\lib\SilLiValueShortint.pas',
  SilLiValueSmallint in '..\..\..\..\..\source\lib\SilLiValueSmallint.pas',
  SilLiValueSingle in '..\..\..\..\..\source\lib\SilLiValueSingle.pas',
  SilLiValueExtended in '..\..\..\..\..\source\lib\SilLiValueExtended.pas',
  SilLiValuePointer in '..\..\..\..\..\source\lib\SilLiValuePointer.pas',
  SilLmDataType in '..\..\..\..\..\source\lib\SilLmDataType.pas',
  SilLhDataType in '..\..\..\..\..\source\lib\SilLhDataType.pas',
  SilLgDataTypeDefs in '..\..\..\..\..\source\lib\SilLgDataTypeDefs.pas',
  SilLkDataHandler in '..\..\..\..\..\source\lib\SilLkDataHandler.pas',
  SilLmDataHandler in '..\..\..\..\..\source\lib\SilLmDataHandler.pas',
  SilBeDataType in '..\..\..\..\..\source\lib\SilBeDataType.pas',
  SilBtDataType in '..\..\..\..\..\source\lib\SilBtDataType.pas',
  SilLmDataTypeList in '..\..\..\..\..\source\lib\SilLmDataTypeList.pas',
  SilLiDataType in '..\..\..\..\..\source\lib\SilLiDataType.pas',
  SilLvDataTypeList in '..\..\..\..\..\source\lib\SilLvDataTypeList.pas',
  SilLfDataTypeList in '..\..\..\..\..\source\lib\SilLfDataTypeList.pas',
  SilLmDataTypeAnsiString in '..\..\..\..\..\source\lib\SilLmDataTypeAnsiString.pas',
  SilLmDataTypeSmallint in '..\..\..\..\..\source\lib\SilLmDataTypeSmallint.pas',
  SilLmDataTypeLongInt in '..\..\..\..\..\source\lib\SilLmDataTypeLongInt.pas',
  SilLmDataTypeSingle in '..\..\..\..\..\source\lib\SilLmDataTypeSingle.pas',
  SilLmDataTypeDouble in '..\..\..\..\..\source\lib\SilLmDataTypeDouble.pas',
  SilLmDataTypeCurrency in '..\..\..\..\..\source\lib\SilLmDataTypeCurrency.pas',
  SilLmDataTypeDateTime in '..\..\..\..\..\source\lib\SilLmDataTypeDateTime.pas',
  SilLmDataTypeWideString in '..\..\..\..\..\source\lib\SilLmDataTypeWideString.pas',
  SilLmDataTypeDispatch in '..\..\..\..\..\source\lib\SilLmDataTypeDispatch.pas',
  SilLmDataTypeVariant in '..\..\..\..\..\source\lib\SilLmDataTypeVariant.pas',
  SilLmDataTypeExtended in '..\..\..\..\..\source\lib\SilLmDataTypeExtended.pas',
  SilLmDataTypeShortInt in '..\..\..\..\..\source\lib\SilLmDataTypeShortInt.pas',
  SilLmDataTypeWord in '..\..\..\..\..\source\lib\SilLmDataTypeWord.pas',
  SilLmDataTypeLongWord in '..\..\..\..\..\source\lib\SilLmDataTypeLongWord.pas',
  SilLmDataTypeLargeInt in '..\..\..\..\..\source\lib\SilLmDataTypeLargeInt.pas',
  SilLmDataTypeGuid in '..\..\..\..\..\source\lib\SilLmDataTypeGuid.pas',
  SilLmDataTypeClass in '..\..\..\..\..\source\lib\SilLmDataTypeClass.pas',
  SilLmDataTypeObject in '..\..\..\..\..\source\lib\SilLmDataTypeObject.pas',
  SilLmDataTypeBoolean in '..\..\..\..\..\source\lib\SilLmDataTypeBoolean.pas',
  SilLmDataTypeByte in '..\..\..\..\..\source\lib\SilLmDataTypeByte.pas',
  SilLfDataHandler in '..\..\..\..\..\source\lib\SilLfDataHandler.pas',
  SilLhValue in '..\..\..\..\..\source\lib\SilLhValue.pas',
  SilLdDataType in '..\..\..\..\..\source\lib\lc\sp\SilLdDataType.pas',
  SilLsValue in '..\..\..\..\..\source\lib\SilLsValue.pas',
  SilLgValueClasses in '..\..\..\..\..\source\lib\SilLgValueClasses.pas',
  SilLdDataHandler in '..\..\..\..\..\source\lib\lc\sp\SilLdDataHandler.pas';

{$R *.res}

begin
  MemChk;
  
  Application.Initialize;
  Application.CreateForm(TFormTestValueMain, FormTestValueMain);
  Application.Run;
end.
