unit FmTestBaseListStringEvents;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs, StdCtrls,

  Sil;

type
  TFormTestEvents = class(
    TForm,
    IUnknown,     // needed by older versions of Delphi
    IListEvents   // implements the required events
    )
    Display: TMemo;
    Button1: TButton;
    Button2: TButton;
    Button3: TButton;
    procedure FormCreate(Sender: TObject);
    procedure Button1Click(Sender: TObject);
    procedure Button2Click(Sender: TObject);
    procedure Button3Click(Sender: TObject);
    procedure FormDestroy(Sender: TObject);
    procedure FormClick(Sender: TObject);
  private
    procedure OnListAdd(const List: IList; Index: Integer);
    procedure OnListInsert(const List: IList; Index: Integer);
    procedure OnListDelete(const List: IList; Index: Integer);
  public
    l: IStringList;
  end;

var
  FormTestEvents: TFormTestEvents;


implementation

{$R *.DFM}

procedure TFormTestEvents.FormCreate(Sender: TObject);
begin
  l := Sil.List.StringList;
  // connect to the events generated by 'l'
  Sil.Sink.Connect(l, Self);
end;

procedure TFormTestEvents.FormDestroy(Sender: TObject);
begin
  // disconnect from 'l'
  Sil.Sink.Disconnect(l, Self);
end;

procedure TFormTestEvents.FormClick(Sender: TObject);
begin
  Display.lines.Clear;
end;

procedure TFormTestEvents.OnListAdd(const List: IList; Index: Integer);
begin
// here we receive a notification of a new item
  Display.lines.add(Format('agregado: %d count:%d', [Index, List.Count]));
end;

procedure TFormTestEvents.OnListDelete(const List: IList; Index: Integer);
begin
// here we receive a notification of a deleted item
  Display.lines.add('borrado: ' + Int.ToStr(Index));
end;

procedure TFormTestEvents.OnListInsert(const List: IList; Index: Integer);
begin
// here we receive a notification of an inserted item
  Display.lines.add('insert: ' + Int.ToStr(Index));
end;

procedure TFormTestEvents.Button1Click(Sender: TObject);
begin
// when we add an item the StringList fires the events 
  l.Add('uno');
end;

procedure TFormTestEvents.Button2Click(Sender: TObject);
begin
// when we remove any item the StringList fires the events
  l.Delete(0);
end;

procedure TFormTestEvents.Button3Click(Sender: TObject);
begin
// when we clear the StringList she fires the delete event for every item
  l.Clear;
end;

end.
